Implemented first task by adding new model, its repository class and …
f3ops3/course-project pull request #1
Opened 2024-09-21 20:18 UTC by f3ops3

…service

2024-09-22 17:47 UTC, Elena-Bruyako requested changes
see comments

2024-09-22 17:47 UTC, Elena-Bruyako commented on src/main/java/springweb/courseproject/repository/BookRepositoryImpl.java
> +            throw new RuntimeException("Couldn't save a book = " + book, e);
```suggestion
            throw new DataProcessingException("Couldn't save a book = " + book, e);
```

2024-09-22 17:47 UTC, Elena-Bruyako commented on src/main/java/springweb/courseproject/repository/BookRepositoryImpl.java
> +    }
```suggestion
@Repository
@RequiredArgsConstructor
public class BookRepositoryImpl implements BookRepository {
    private final SessionFactory sessionFactory;
```

2024-09-22 17:47 UTC, Elena-Bruyako commented on src/main/java/springweb/courseproject/repository/BookRepositoryImpl.java
> +            throw new RuntimeException("Couldn't find all books", e);
```suggestion
            throw new DataProcessingException("Couldn't find all books", e);
```

2024-09-22 17:47 UTC, Elena-Bruyako commented on src/main/java/springweb/courseproject/service/BookServiceImpl.java
> +@Service
```suggestion
@Service
@RequiredArgsConstructor
```

2024-09-22 17:47 UTC, Elena-Bruyako commented on src/main/java/springweb/courseproject/service/BookServiceImpl.java
> +    public BookServiceImpl(BookRepository bookRepository) {
remove constructor

2024-09-22 17:47 UTC, Elena-Bruyako commented on src/main/java/springweb/courseproject/service/BookServiceImpl.java
> +    private BookRepository bookRepository;
```suggestion
    private final BookRepository bookRepository;
```

2024-09-23 10:47 UTC, okuzan approved these changes

2024-09-23 13:26 UTC, merged