Added category model
f3ops3/course-project pull request #11
Opened 2024-10-15 00:49 UTC by f3ops3

Added category model, implemented corresponding service and controller. Added dtos and modified existing code to work correctly with the new one.

2024-10-15 08:18 UTC, JJJazl requested changes

2024-10-15 08:18 UTC, JJJazl commented on src/main/java/springweb/courseproject/controller/CategoryController.java
> +    }
You can add a status code using @ResponseStatus. Check an appropriate status for POST request

2024-10-15 08:18 UTC, JJJazl commented on src/main/java/springweb/courseproject/controller/CategoryController.java
> +    }
The same with status code

2024-10-15 13:57 UTC, Elena-Bruyako requested changes
see comments

2024-10-15 13:57 UTC, Elena-Bruyako commented on src/main/java/springweb/courseproject/controller/CategoryController.java
> +    public CategoryResponseDto createCategory(@RequestBody CreateCategoryRequestDto categoryDto) {
```suggestion
    public CategoryResponseDto createCategory(@RequestBody @Valid CreateCategoryRequestDto categoryDto) {
```

2024-10-15 13:57 UTC, Elena-Bruyako commented on src/main/java/springweb/courseproject/controller/CategoryController.java
> +                                              @RequestBody CreateCategoryRequestDto categoryDto) {
```suggestion
                                              @RequestBody @Valid CreateCategoryRequestDto categoryDto) {

```

2024-10-15 13:57 UTC, Elena-Bruyako commented on src/main/java/springweb/courseproject/dto/book/CreateBookRequestDto.java
> +    private Set<Long> categoryIds;
```suggestion
    @NotEmpty
    private Set<Long> categoryIds;
```

2024-10-15 13:57 UTC, Elena-Bruyako commented on src/main/java/springweb/courseproject/dto/category/CreateCategoryRequestDto.java
> +    private String name;
you can also validate size for both fields

2024-10-15 13:57 UTC, Elena-Bruyako commented on src/main/java/springweb/courseproject/repository/book/BookRepository.java
> +    @Override
remove @Override everywhere in repo

2024-10-15 13:57 UTC, Elena-Bruyako commented on src/main/java/springweb/courseproject/service/category/CategoryServiceImpl.java
> +        Optional<Category> category = categoryRepository.findById(id);
actually this query is redundant (not mistake). It depends on requirements, but if you don't have category Hibernate delete it silently
Bad practice to use category.get() without any checking isPresent for example

2024-10-16 06:05 UTC, liliia-ponomarenko approved these changes
Good job! But fix my comments before merging;)

2024-10-16 06:05 UTC, liliia-ponomarenko commented on src/main/java/springweb/courseproject/controller/BookController.java
> +    @ResponseStatus(HttpStatus.OK)
it's default response status

2024-10-16 06:05 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/08-create-categories-table.yaml
> +
only one empty line at the end of the file (check other files)

2024-10-16 10:48 UTC, merged