Added orders logic
f3ops3/course-project pull request #13
Opened 2024-10-21 08:45 UTC by f3ops3

Added orders logic by implementing services, repositories, models, mappers and controller classes. Added "/api" route

2024-10-21 09:58 UTC, JJJazl requested changes

2024-10-21 09:58 UTC, JJJazl commented on src/main/java/springweb/courseproject/controller/OrderController.java
> +    @PostMapping
Please, add corresponding status code for POST method

2024-10-21 09:58 UTC, JJJazl commented on src/main/java/springweb/courseproject/controller/OrderController.java
> +    public OrderResponseDto updateOrder(
```suggestion
    public OrderResponseDto updateOrder(

```

2024-10-21 09:58 UTC, JJJazl commented on src/main/java/springweb/courseproject/dto/order/PatchOrderRequestDto.java
> +public class PatchOrderRequestDto {
```suggestion
public class UpdateOrderRequestDto {

```

2024-10-21 09:58 UTC, JJJazl commented on src/main/java/springweb/courseproject/service/order/OrderService.java
> +    OrderResponseDto patchOrder(Long orderId, PatchOrderRequestDto patchOrderRequestDto);
```suggestion
    OrderResponseDto updateOrder(Long orderId, PatchOrderRequestDto patchOrderRequestDto);

```

2024-10-21 09:58 UTC, JJJazl commented on src/main/java/springweb/courseproject/service/order/OrderServiceImpl.java
> +        );
```suggestion
Set<OrderItems> orderItems = cart.getCartItems().stream()
                .map(cartItem -> {
                    OrderItem orderItem = orderItemMapper.toOrderItem(cartItem);
                    orderItem.setOrder(order);
                    return orderItem;
                })
                .collect(Collectors.toSet())
        order.setOrderItems(orderItems);
```

2024-10-21 09:58 UTC, JJJazl commented on src/main/java/springweb/courseproject/service/order/OrderServiceImpl.java
> +        );
```suggestion
BigDecimal total = cart.getCartItems().stream()
                .map(cartItem -> cartItem.getBook().getPrice().multiply(
                        BigDecimal.valueOf(cartItem.getQuantity())))
                .reduce(BigDecimal.ZERO, BigDecimal::add);
        order.setTotal(total);
```

2024-10-22 07:08 UTC, liliia-ponomarenko requested changes
Good job! Let’s improve your solution ;)

2024-10-22 07:08 UTC, liliia-ponomarenko commented on src/main/java/springweb/courseproject/service/order/OrderServiceImpl.java
> +                () -> new EntityNotFoundException("Shopping cart with user id "
this exception should return a 404 response status

2024-10-22 07:08 UTC, liliia-ponomarenko commented on src/main/java/springweb/courseproject/service/order/OrderServiceImpl.java
> +            throw new DataProcessingException("You can't place an order with empty shopping cart");
the same 400 response status should be return

2024-10-22 07:08 UTC, liliia-ponomarenko commented on src/main/java/springweb/courseproject/service/order/OrderServiceImpl.java
> +    public OrderResponseDto createOrder(Long userId, CreateOrderRequestDto createOrderRequestDto) {
Let’s  use Transactional

2024-10-22 07:08 UTC, liliia-ponomarenko commented on src/main/java/springweb/courseproject/service/order/OrderServiceImpl.java
> +        order.setTotal(total);
Let’s  move it to the private method

2024-10-22 07:08 UTC, liliia-ponomarenko commented on src/main/java/springweb/courseproject/service/order/OrderServiceImpl.java
> +        return orderMapper.toDto(orderRepository.save(order));
Don’t  forget to clear the user's shopping cart

2024-10-22 07:08 UTC, liliia-ponomarenko commented on src/main/java/springweb/courseproject/service/order/OrderServiceImpl.java
> +        checkIfOrderBelongsToUser(order, userId);
You can check on request level 
```suggestion
        Order order = orderRepository.findByIdAndUserId(orderId, userId).orElseThrow(
                () -> new EntityNotFoundException("Order with order id " + orderId + " not found...")
        );
```

2024-10-22 07:08 UTC, liliia-ponomarenko commented on src/main/java/springweb/courseproject/service/order/OrderServiceImpl.java
> +        checkIfOrderBelongsToUser(order, userId);
the same

2024-10-22 07:08 UTC, liliia-ponomarenko commented on src/main/java/springweb/courseproject/service/order/OrderServiceImpl.java
> +                .findFirst();
Can you refactor your query and avoid using this filter? (Find order item by id)

2024-10-22 07:12 UTC, liliia-ponomarenko reviewed
One more thing, I noticed you link to the mate academy chekcstyle plugin. Add the checks file to your project directly.

2024-10-22 14:13 UTC, okuzan approved these changes

2024-10-22 16:17 UTC, merged