Changed book repository, added new methods and endpoints in bookServi…
f3ops3/course-project pull request #3
Opened 2024-09-27 19:13 UTC by f3ops3

…ce and BookController, implemented soft delete concept, added liquibase support.

2024-09-28 06:48 UTC, Elena-Bruyako requested changes
Good job! Let's improve it

2024-09-28 06:48 UTC, Elena-Bruyako commented on src/main/java/springweb/courseproject/repository/BookRepository.java
> +    //Book updateBookById(Long id, Book book);
remove commented code

2024-09-28 06:48 UTC, Elena-Bruyako commented on src/main/java/springweb/courseproject/service/BookService.java
> +    BookDto updateBookById(long id, CreateBookRequestDto book);
```suggestion
    BookDto updateBookById(Long id, CreateBookRequestDto book);

```

2024-09-28 06:48 UTC, Elena-Bruyako commented on src/main/java/springweb/courseproject/service/BookService.java
> +    void deleteBookById(long id);
```suggestion
    void deleteBookById(Long id);
```

2024-09-28 06:48 UTC, Elena-Bruyako commented on src/main/java/springweb/courseproject/repository/BookRepository.java
> +@Repository
```suggestion
```

2024-09-28 06:48 UTC, Elena-Bruyako commented on src/main/java/springweb/courseproject/service/BookServiceImpl.java
> +        bookToUpdate = bookMapper.updateBook(book, bookToUpdate);
```suggestion
        Book book = bookRepository.findById(id).orElseThrow(
                () -> new EntityNotFoundException("Couldn't find book with id = " + id));
        bookMapper.updateBook(bookDto, book);
```

2024-09-28 06:48 UTC, Elena-Bruyako commented on src/main/java/springweb/courseproject/service/BookServiceImpl.java
> +    public BookDto updateBookById(long id, CreateBookRequestDto book) {
```suggestion
    public BookDto updateBookById(long id, CreateBookRequestDto bookDto) {
```

2024-09-28 06:48 UTC, Elena-Bruyako commented on src/main/java/springweb/courseproject/service/BookServiceImpl.java
> +        return bookMapper.toDto(bookRepository.save(bookToUpdate));
```suggestion
        return bookMapper.toDto(bookRepository.save(book));

```

2024-09-28 06:48 UTC, Elena-Bruyako commented on src/main/java/springweb/courseproject/mapper/BookMapper.java
> +    Book updateBook(CreateBookRequestDto dto, @MappingTarget Book book);
```suggestion
    void updateBook(CreateBookRequestDto bookDto, @MappingTarget Book book);
```

2024-09-28 06:48 UTC, Elena-Bruyako commented on src/main/java/springweb/courseproject/service/BookServiceImpl.java
> +        Book bookToDelete = bookRepository.findById(id).orElseThrow(
if there are no requirements to throw an exception during delete, this request to DB could be redundant.

2024-09-29 17:13 UTC, Elena-Bruyako requested changes
see comments

2024-09-29 17:13 UTC, Elena-Bruyako commented on src/main/java/springweb/courseproject/service/BookServiceImpl.java
> +        bookRepository.findById(id).ifPresent(bookRepository::delete);
```suggestion
        bookRepository.findById(id);

```

2024-09-29 17:13 UTC, Elena-Bruyako commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> +                    nullable: false
add an empty line at the end of file

2024-09-30 09:59 UTC, MentorMateAcademy approved these changes

2024-09-30 12:08 UTC, merged