Created User entity, related repository, mapper, DTOs, and a registra…
f3ops3/course-project pull request #8
Opened 2024-10-06 11:36 UTC by f3ops3

…tion endpoint.

2024-10-06 11:41 UTC, Elena-Bruyako requested changes
add ci.yml file first to the project

2024-10-07 08:38 UTC, ahoienko requested changes
Nice, left minor comments)

2024-10-07 08:38 UTC, ahoienko commented on src/main/java/springweb/courseproject/service/user/UserServiceImpl.java
> +            throw new RegistrationException("User already exists");
```suggestion
            throw new RegistrationException("User with email: " + email + " already exists");

```

2024-10-07 08:38 UTC, ahoienko commented on src/main/java/springweb/courseproject/validation/user/EmailValidator.java
> +    }
Is it necessary to write custom annotation for such logic? Please investigate I`m 99% sure that such annotation already exists

2024-10-07 08:38 UTC, ahoienko commented on src/main/resources/db/changelog/changes/02-create-users-table.yaml
> +                  type: VARCHAR(255)
Add empty line

2024-10-08 07:03 UTC, liliia-ponomarenko approved these changes
Good job!

2024-10-08 07:03 UTC, liliia-ponomarenko commented on src/main/resources/db/changelog/changes/02-create-users-table.yaml
> +
```suggestion
```
only one empty line ;)

2024-10-08 07:27 UTC, merged